export const REGISTER = 'REGISTER';
export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS';
export const FETCH_RESTAURANT_BY_ID = 'FETCH_RESTAURANT_By_ID';
export const FETCH_MENU_ITEMS_BY_ID = 'FETCH_MENU_ITEMS_By_ID';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
